
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev?serverTimezone=America/Chicago&useSSL=false&allowPublicKeyRetrieval=true
    username: sfg_dev_user
    password: guru
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: guru_database_create.sql